name: Test Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2 nginx certbot python3-certbot-apache python3-certbot-nginx netcat-openbsd
          
      - name: Make script executable
        run: chmod +x ./lecbh.sh
      
      - name: Run tests in dry-run mode
        run: sudo ./lecbh.sh --dry-run --unattended --verbose
        
      - name: Test with Apache
        run: |
          # Start Apache
          sudo systemctl start apache2
          sudo systemctl status apache2
          
          # Run test with Apache
          sudo ./lecbh.sh --dry-run --unattended --verbose
          
      - name: Test with Nginx
        run: |
          # Stop Apache and start Nginx
          sudo systemctl stop apache2
          sudo systemctl start nginx
          sudo systemctl status nginx
          
          # Run test with Nginx (explicitly specify)
          sudo ./lecbh.sh --dry-run --unattended --verbose --server nginx