name: Test Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Setup Docker Compose
        uses: docker/compose-action@v2
        
      - name: Run tests
        run: |
          docker-compose up -d
          sleep 5
          docker-compose exec -T lecbh-test /app/lecbh.sh --dry-run --unattended
          docker-compose down