name: Test Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-compose-${{ hashFiles('**/Dockerfile', '**/docker-compose.yml') }}
          restore-keys: |
            ${{ runner.os }}-docker-compose-
      
      - name: Build Docker Compose images with cache
        run: |
          # Export buildx cache to Docker
          docker buildx create --use
          docker compose build --build-arg BUILDKIT_INLINE_CACHE=1
      
      - name: Run tests
        run: |
          # Start containers
          docker compose up -d
          
          # Wait a bit longer for container to fully initialize
          sleep 10
          
          # Check container status
          docker compose ps
          
          # Check container logs to see why it might be exiting
          docker compose logs
          
          # Check if container is actually running
          if docker compose ps --status running | grep -q lecbh-test; then
            echo "Container is running, proceeding with tests"
            # Run the test command
            docker compose exec -T lecbh-test /app/lecbh.sh --dry-run --unattended
          else
            echo "Container is not running, checking logs"
            docker compose logs lecbh-test
            exit 1
          fi
          
          # Clean up
          docker compose down